version: 2
snapshot:
  widths:
    - 1280
  minHeight: 1024
discovery:
  allowedHostnames: []
  disallowedHostnames: []
  disableCache: false
  networkIdleTimeout: 700
  launch-options:
    headless: false # default
  concurrency: 1
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
  stripExtensions: false
