version: 2
snapshot:
  widths:
    - 375
    - 1280
  minHeight: 1024
  percyCSS: |
    .change-font{
      font-family: "Times New Roman", Times, serif;
    }
discovery:
  allowedHostnames: ["localhost", "bstackdemo.com"]
  networkIdleTimeout: 100
  disableCache: false
  launch-options:
    headless: true
